version: '3'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - DATABASE_USER=rm552504
      - DATABASE_PWD=100997
    depends_on:
      - oracle-db
