CREATE SEQUENCE SEQ_ALERTA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE tbl_alertas (
    alerta_id INTEGER DEFAULT SEQ_ALERTA.NEXTVAL NOT NULL,
    tipo VARCHAR2(50),
    localizacao VARCHAR2(100),
    timestamp TIMESTAMP,
    PRIMARY KEY (alerta_id)
);
